---

apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  POSTGRES_PASSWORD: cG9zdGdyZXM= # postgres base64
  RABBIT_MQ_PASSWORD: Z3Vlc3Q= # guest base64
  RABBIT_MQ_USER: Z3Vlc3Q=
  POSTGRES_USER: cG9zdGdyZXM=